import Navbar from "./components/Navbar/navbar";
import { Nabla } from "next/font/google";
import Footer from "./components/Footer/footer";
import { SessionProvider } from "next-auth/react";
import { headers } from "next/headers";
import type { Metadata } from "next";

import "./globals.css";
export const metadata: Metadata = {
  title: "Next App - SaaS",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
      </head>
      <body className="bg-gray-100">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
